jaja_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story6/', include('story6.urls', namespace='story6'))
]

story3/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('resume/', views.resume, name='resume'),
    path('activity/', views.activity, name='activity'),
    path('story1/', views.story1, name='story1'),
    path('matkul/', views.matkul, name='matkul'),
    path('dataMatkul/', views.dataMatkul, name='dataMatkul'),
    path('delete/<id_matkul>/', views.delMatkul, name='delMatkul'),
]

story6/urls.py
from django.urls import path, include
from . import views

app_name = 'story6'

urlpatterns = [
    path('indexStory6/', views.indexStory6, name='indexStory6'),
    path('addActivity/', views.addActivity, name='addActivity'),
    path('listActivity/', views.listActivity, name='listActivity'),
    path('registerPerson/<int:id_person>/', views.registerPerson, name='registerPerson'),
    # path('delete/<int:id_persondel>/', views.deletePerson, name='deletePerson'),
]

story3/models.py
from django.db import models

class Matkul(models.Model):
    courseName = models.CharField(max_length=50)
    lecturerName = models.CharField(max_length=50)
    sks = models.IntegerField()
    courseDesc = models.CharField(max_length=200)
    term = models.CharField(max_length=50)
    room = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)

story6/models.py
from django.db import models

class Activity(models.Model):
    activity_name = models.CharField(max_length=200)
    activity_desc = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.activity_name

class Person(models.Model):
    person_name = models.CharField(max_length=200)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True, blank=True)

    # def __str__(self):
    #     return self.person_name

story3/forms.py
# from django.forms import ModelForm
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = '__all__'
        
    courseName = forms.CharField(label='Course Name', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_courseName'}))
    lecturerName = forms.CharField(label='Lecturer Name', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_lecturerName'}))
    sks = forms.IntegerField(label='SKS', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_sks'}))
    courseDesc = forms.CharField(label='Description', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_courseDesc'}))
    term = forms.CharField(label='Term', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_term'}))
    room = forms.CharField(label='Room', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_room'}))

story6/forms.py
from django import forms

class ActivityForm(forms.Form):
    activity_form = forms.CharField(
        label="Nama kegiatan",
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60'
            }
        )
    )

    activity_desc = forms.CharField(
        label="Deskripsi kegiatan",
        max_length=200,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control w-60'
            }
        )
    )

class PersonForm(forms.Form):
    person_name = forms.CharField(
        label="Nama",
        max_length=200,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60'
            }
        )
    )

story3/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import MatkulForm
from .models import Matkul

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def resume(request):
    return render(request, 'resume.html')

def activity(request):
    return render(request, 'activity.html')

def story1(request):
    return render(request, 'story1.html')

def matkul(request):
    form = MatkulForm()

    if request.method == 'POST':
        print(request.POST)
        form = MatkulForm(request.POST)
        
        if form.is_valid():
            Matkul.objects.create(
                courseName = request.POST['courseName'],
                lecturerName = request.POST['lecturerName'],
                sks = request.POST['sks'],
                courseDesc = request.POST['courseDesc'],
                term = request.POST['term'],
                room = request.POST['room'],
            )

            return HttpResponseRedirect('/matkul')
            
    context = {'form':form.as_table}
    return render(request, 'matkul.html', context)

def dataMatkul(request):
    data_matkul = Matkul.objects.all()
    context = {'matkuls':data_matkul}
    return render(request, 'dataMatkul.html', context)

def delMatkul(request, id_matkul):
    Matkul.objects.filter(id=id_matkul).delete()
    return HttpResponseRedirect('/dataMatkul')

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import ActivityForm, PersonForm
from .models import Activity, Person

def indexStory6(request):
    return render(request, 'indexStory6.html')

def addActivity(request):
    form_activity = ActivityForm()

    if request.method == 'POST':
        # print(request.POST)
        form_activity = ActivityForm(request.POST)
        
        if form_activity.is_valid():
            data = form_activity.cleaned_data
            activity = Activity()
            activity.activity_form = data['activity_form']
            activity.activity_desc = data['activity_desc']
            activity.save()
            # Activity.objects.create(
            #     activity_name = request.POST['activity_name'],
            #     activity_desc = request.POST['activity_desc']
            # )
            return redirect('/story6/addActivity')
            
    context = {'form':form_activity.as_table}
    return render(request, 'addActivity.html', context)

def listActivity(request):
    activity = Activity.objects.all()
    person = Person.objects.all()
    # return HttpResponseRedirect('/story6/listActivity')
    return render(request, 'listActivity.html', {'activity': activity, 'person': person})

def registerPerson(request, id_person):
    form_person = PersonForm()

    if request.method == 'POST':
        form_person = PersonForm(request.POST)

        if form_person.is_valid():
            data = form_person.cleaned_data
            person = Person()
            person.person_name = request.POST['person_name']
            person.activity = Activity.objects.get(id=id_person)
            person.save()
            return redirect('/story6/registerPerson')
        
        # else:
        #     return render(request, 'story6/register.html', {'form': form_person, 'status': 'failed'})
    
    # else:
    #     return render(request, 'story6/registerPerson.html', {'form': form_person})

    context = {'form':form_person.as_table}
    return render(request, 'registerPerson.html', context)

# def deletePerson(request, id_persondel):
#     Person.objects.filter(id=id_persondel).delete()
#     return redirect('/story6/listActivity')

story3/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>about - najwa lathifah</title>
</head>
<style>
    #about {
        font-weight: bold;
    }
</style>
<body>
    <div class="container" style="text-align: center;">
        <div class="desc">
            <div>
                <img style="width: 280px;" src="{% static 'jaja.jpg' %}">
            </div>
            <div id="text" style="margin-left: 5vw;">
                <h2 style="margin-top: 0;">I’m Najwa, but people often call me <b>Jaja</b>. I’m an undergraduate student majoring in <b>Information System at Universitas Indonesia</b> and now I’m on my 2nd year. 
                    <br>In college, I learn about programming, business, and management. Interesting, isn’t it? Apart from study, I also join an organization and some comittees in my faculty.</h2>
            </div>
        </div>
    </div>

    <div class="things">
        <h3 style="padding-top: 17px;"><b>things i love;<br>things i love to do;<br>things i'm interested in</b></h3>
        <div class="love" style="margin-top: 28px;"><h3 style="text-align: justify;">I have a lot of hobbies. 
            I love to sing, even though i don’t have a good voice. 
            I also like to watch TV series or kor/thai drama. Unfortunately, it’s so hard to do that some kind of fun because 
            nowadays i have a lot of tasks to do and don’t have much leisure time.</h3>
        </div>
        <div class="love" style="margin-top: 22px;"><h3 style="text-align: justify;">I’m not (yet) a skillful person. 
            But i do have some things that got my interest, such as technology, business, and finance/accounting. In technology, 
            i put my interest on project/product management, UX, and data. As in business, i got my interest by seeing a lot of 
            start-up CEOs and get fascinated about their successful because surely they have great leadership and management skills 
            (which motivate me to develop myself even more). Last but not least, i have interest in finance/accounting because i have 
            been dealing with money management related since junior high school and i always had a lot of fun while doing that. 
            I think it will be much better if i have time to study economy/accounting to upgrade this skill.</h3>
        </div>
        <div class="love" style="margin-top: 22px;"><h3 style="text-align: justify;">Here comes the last parapgraph. 
            I’m a kind of person who gets love or attracted easily to someone or something. 
            These gifs below will show you who usually makes me fangirling.</h3>
            <br>
            <br>
        </div>
        <img src="{% static 'likey3.gif' %}" style="margin-top: 0px; width: 100%;">
    </div>
</body>
{% endblock %}

story3/templates/activity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>activity - najwa lathifah</title>
</head>
<style>
    .placeholder {
        background-color: #BAABED;
    }
    #activity {
        font-weight: bold;
    }
</style>
<body style="background-color: #BAABED;">
    <div class="containerAct">
        <h3 style="font-size: 22px;"><em><strong>FIRST HALF OF 2020</strong></em></h3>
        <img src="{% static '1sthalfof2020.gif' %}" style="margin-top: 0px; width: 100%;">
        <h2 class="love" style="text-align: center;"><em>attend suju’s concert - finance cf12 bidding and photoshoot - first meet bem - bem’s meeting - indonesia master - vidcall and bonding with friends - event div wisgan 2020 - bidding personality wisgan 2021</em></h2>
    </div>
    <div class="containerAct">
        <h3 style="font-size: 22px;"><em><strong>SECOND HALF OF 2019</strong></em></h3>
        <img src="{% static '2ndhalfof2019.gif' %}" style="margin-top: 0px; width: 100%;">
        <h2 class="love" style="text-align: center;"><em>rotunda with jakun - won vg contest on newbie cup - attend westlife’s concert - sbf gath - tortilla - parade - karaoke ot11 - my birthday surprise - my first comittee in pacil (wisgan!) - syntax</em></h2>
    </div>
    <div class="containerAct" style="margin-bottom: 150px;">
        <h3 style="font-size: 22px;"><em><strong>FIRST HALF OF 2019</strong></em></h3>
        <img src="{% static '1sthalfof2019.gif' %}" style="margin-top: 0px; width: 100%;">
        <h2 class="love" style="text-align: center;"><em>graduation - osis regen - osis farewell - hakrab - impulsive trip to ancol - future park jkt - yearbook photoshoot - indonesia master - my first pemilu</em></h2>
    </div>
</body>
{% endblock %}

story3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}">
</head>
<body>
    <div class="placeholder">
        <nav class="navbar">
            <div class="container-navbar" id="theNav" style="margin-top: 15px;">
                <a id="home" href = "{% url 'story3:index' %}">home</a>
                <a id="about" href = "{% url 'story3:about' %}">about</a>
                <a id="resume" href = "{% url 'story3:resume' %}">resume</a>
                <a id="activity" href = "{% url 'story3:activity' %}">activity</a>
                <a id="story1" href = "{% url 'story3:story1' %}">story#1</a>
            </div>
        </nav>
    </div>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <footer style="background-color: #966FD6;">
        <div class = "socmed">
            <h3 style="font-size: 18px; padding-top: 10px;">contact me</h3>
            <a class="logo" href="https://www.instagram.com/najwalathifah/?hl=en"><img src="{% static 'instagram.png' %}"></a>
            <a class="logo" id="linkedin" href="https://www.linkedin.com/in/najwalathifah/"><img src="{% static 'linkedin.svg' %}"></a>
            <a class="logo" href="mailto:najwalathifah11@gmail.com"><img src="{% static 'email.png' %}"></a>
            <h3 style="font-size: 10px; padding-top: 15px;">©2020 Najwa Lathifah, All Rights Reserved</h3>
        </div>
    </footer>
</body>
</html>

story3/templates/dataMatkul.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>college course - najwa lathifah</title>
</head>
<body style="text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 50px;">
        <table class="table" style="font-size: 14px; text-align: left;">
            <thead>
                <tr>
                    <th scope="col">Course Name</th>
                    <th scope="col">Lecturer Name</th>
                    <th scope="col">SKS</th>
                    <th scope="col">Description</th>
                    <th scope="col">Term</th>
                    <th scope="col">Room</th>
                    <th scope="col">Delete?</th>
                </tr>
            </thead>
            <tbody>
                {% for matkul in matkuls %}
                <tr>
                    <td>{{ matkul.courseName }}</td>
                    <td>{{ matkul.lecturerName }}</td>
                    <td>{{ matkul.sks }}</td>
                    <td>{{ matkul.courseDesc }}</td>
                    <td>{{ matkul.term }}</td>
                    <td>{{ matkul.room }}</td>
                    <td>
                        <a href="/delete/{{matkul.id}}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2 style="font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>if you want to go back</em></b></h2>
        <a style="font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story3:matkul' %}">click me</a>
    </div>
</body>
{% endblock %}

story3/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>najwa lathifah</title>
</head>
<style>
    #home {
        font-weight: bold;
    }
</style>
<body style="text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 50px;">
        <h1>Najwa Lathifah Ulima</h1>
        <h2 style="text-align: center;">Hello! Welcome to my personal website😊<br>
        Let’s have a look around and i hope you enjoy the ride!</h2>

        <h2 style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>new feature</em></b></h2>
        <a style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story3:matkul' %}">college courses</a>

        <h2 style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>STORY 6</em></b></h2>
        <a style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story6:indexStory6' %}">my activities</a>

    </div>
</body>
{% endblock %}

story3/templates/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>college course - najwa lathifah</title>
</head>
<body style="align-items: center; text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 5px; text-align: left;">
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <input type="submit" style="margin-left: 320px; background-color: palevioletred;">
        </form>
    </div style="align-items: center">
    <div class="container-fluid" style="padding-bottom: 50px; align-items: center;">
        <h2 style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>click below to see the course list</em></b></h2>
        <a style= "width:100% ;text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story3:dataMatkul' %}">here</a>
    </div>
</body>
{% endblock %}

story3/templates/resume.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>resume - najwa lathifah</title>
</head>
<style>
    #resume {
        font-weight: bold;
    }
</style>
<body style="align-items: center;">
    <div class="row">
        <div class="col1" style="margin-right: 87px;">
            Education
        </div>
        <div class="col2" style="margin-right: 70px;">
            <b>Universitas Indonesia</b><br>Information System
            <br>
            <br>
            <b>SMAN 3 Depok</b><br>Math and Natural Science
            <br>
            <br>
            <b>SMPN 3 Depok</b>
        </div>
        <div class="col3">
            2019 - Present
            <br>
            <br>
            <br>
            2016 - 2019
            <br>
            <br>
            <br>
            2013 - 2016
        </div>
    </div>

    <div class="row">
        <div class="col1">
            Organization
        </div>
        <div class="col2">
            <b>BEM Fasilkom UI</b><br>Staff of Human Resource Development Bureau
            <br>
            <br>
            <b>AIESEC in UI</b><br>Internship member of Finance, Governance, & Legality
            <br>
            <br>
            <b>OSIS SMAN 3 Depok</b><br>Treasurer in 2 years of organization’s period
        </div>
        <div class="col3">
            2020 - Present
            <br>
            <br>
            <br>
            <br>
            Oct 2019 - Dec 2019
            <br>
            <br>
            <br>
            <br>
            2017 - 2019
        </div>
    </div>

    <div class="row" style="margin-bottom: 50px;">
        <div class="col1" style="margin-right: 89px;">
            Volunteer
        </div>
        <div class="col2" style="margin-right: 28px;">
            <b>COMPFEST 12</b><br>Vice Manager of Finance
            <br>
            <br>
            <b>Wisuda Ganjil 2019/2020</b><br>Staff of Event Division
            <br>
            <br>
            <b>28 Smanti Celebration Day</b><br>Treasurer 1
        </div>
        <div class="col3">
            Oct 2019 - Oct 2020
            <br>
            <br>
            <br>
            Dec 2019 - Jan 2020
            <br>
            <br>
            <br>
            Feb 2018 - Sep 2018
        </div>
    </div>
</body>
{% endblock %}

story3/templates/story1.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'story1.css' %}">
    <title>Jaja's Personal Site</title>
</head>
<style>
    .placeholder {
        background-color: #c3aed6;
    }
    #story1 {
        font-weight: bold;
    }
</style>
<body>
    <table cellspacing="25">
        <tr>
            <td><img src="{% static 'jaja2.png' %}" alt="jaja profile picture"></td>
            <td><h1>Najwa Lathifah Ulima</h1>
                <p>Hello! My name is Jaja, an IT undergraduate student who has a strong interest in leadership and technology. Believe it or not, I'm actually (quite) love to code but sometimes my brain doesn't want to cooperate🙄. Apart from studying, I'm actively taking part in student organization and committees in my faculty. </p></td>
        </tr>
    </table>
    <hr size="3">
    <h3>Profile</h3>
    <table cellspacing="5">
        <tbody>
            <tr>
                <td>Name: </td>
                <td>Najwa Lathifah Ulima</td>
            </tr>
            <tr>
                <td>NPM: </td>
                <td>1906398925</td>
            </tr>
            <tr>
                <td>Year of: </td>
                <td>2019</td>
            </tr>
            <tr>
                <td>Major, University: </td>
                <td>Information System, Universitas Indonesia</td>
            </tr>
        </tbody>
    </table>
    <hr size="3">
    <h3>Educational History</h3>
    <table cellspacing="5">
        <tbody>
            <col width="120">
                <tr>
                    <td>2019 - Present</td>
                    <td>Universitas Indonesia</td>
                </tr>
                <tr>
                    <td>2016 - 2019</td>
                    <td>SMAN 3 Depok</td>
                </tr>
                <tr>
                    <td>2013 - 2016</td>
                    <td>SMPN 3 Depok</td>
                </tr>
        </tbody>
    </table>
    <hr size="3">
    <h3>Hobbies</h3>
    <table> 
        <tbody>
            <tr>
                <td>🦥 Procrastinate</td>
            </tr>
            <tr>
                <td>📚 (sometimes) Studying</td>
            </tr>
            <tr>
                <td>📺 Watching TV series</td> 
            </tr>
            <tr>
                <td>🎤 Singing</td> 
            </tr>
            <tr>
                <td>👱‍♀️ Dyeing my hair</td> 
            </tr>
        </tbody>
    </table>
    <hr size="3">
    <h3>Social Media</h3>
    <table cellspacing="5">
        <tbody>
            <col width="120">
                <tr>
                    <td><a href="https://www.instagram.com/najwalathifah/?hl=en">Instagram</a></td>
                </tr>
                <tr>
                    <td><a href="https://www.linkedin.com/in/najwalathifah/">Linkedin</a></td>
                </tr>
                <tr>
                    <td><a href="mailto:najwalathifah11@gmail.com">Email</a></td>
                </tr>
        </tbody>
    </table>
</body>
{% endblock %}

story6/templates/addActivity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>add activity - najwa lathifah</title>
</head>
<body style="align-items: center; text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 5px; text-align: left;">
        <form method="POST" action="{% url 'story6:addActivity' %}">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <input type="submit" style="margin-left: 502px; background-color: palevioletred;">
        </form>
    </div style="align-items: center">
    <div class="container-fluid" style="padding-bottom: 50px; align-items: center;">
        <h2 style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>click below to see my activity list</em></b></h2>
        <a style= "width:100% ;text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story6:listActivity' %}">here</a>
    </div>
</body>
{% endblock %}

story6/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}">
</head>
<body>
    <div class="placeholder">
        <nav class="navbar">
            <div class="container-navbar" id="theNav" style="margin-top: 15px;">
                <a id="home" href = "{% url 'story3:index' %}">home</a>
                <a id="about" href = "{% url 'story3:about' %}">about</a>
                <a id="resume" href = "{% url 'story3:resume' %}">resume</a>
                <a id="activity" href = "{% url 'story3:activity' %}">activity</a>
                <a id="story1" href = "{% url 'story3:story1' %}">story#1</a>
            </div>
        </nav>
    </div>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <footer style="background-color: #966FD6;">
        <div class = "socmed">
            <h3 style="font-size: 18px; padding-top: 10px;">contact me</h3>
            <a class="logo" href="https://www.instagram.com/najwalathifah/?hl=en"><img src="{% static 'instagram.png' %}"></a>
            <a class="logo" id="linkedin" href="https://www.linkedin.com/in/najwalathifah/"><img src="{% static 'linkedin.svg' %}"></a>
            <a class="logo" href="mailto:najwalathifah11@gmail.com"><img src="{% static 'email.png' %}"></a>
            <h3 style="font-size: 10px; padding-top: 15px;">©2020 Najwa Lathifah, All Rights Reserved</h3>
        </div>
    </footer>
</body>
</html>

story6/templates/indexStory6.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>najwa lathifah - Story6</title>
</head>
<body style="text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 50px;">
        <h2 style="font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred; font-size: 28px; font-weight: bold; margin-bottom: 70px;">✨Welcome to Story 6 PPW✨</h2>
        <table class="table">
            <tr>
                <th scope="col">
                    <a href="{% url 'story6:addActivity' %}" style="font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;">Add Activity</a>
                </th>
                <th scope="col">
                    <a href="{% url 'story6:listActivity' %}" style="font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;">List Activity</a>
                </th>
            </tr>
        </table>
    </div>
</body>
{% endblock %}

story6/templates/listActivity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>list activity - najwa lathifah</title>
</head>
<body style="align-items: center; text-align: center;">
    <div class="row w-100 justify-content-center">

        {% for i in activity %}
        <div class="col-4 m-4 p-4 rounded border">
            <ul class="list-group">
                <li class="list-group-item list-group-item-secondary"> <b> {{ i.activity }} </b> </li>
                {% for j in person %}
                {% if j.activity == i %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        {{ j.person_name }}
                        <!-- <button>
                            <a href="{% url 'delete' id_persondel=j.pk %}">x</a>
                        </button> -->
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>

            <div style="font-size: .75em;" class="section-title mx-auto text-center my-3">
                <a href="{% url 'story6:registerPerson' id_person=i.pk %}" class="button">
                    <button> register </button>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

</section>
</body>
{% endblock %}

story6/templates/registerPerson.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>regist - najwa lathifah</title>
</head>
<body style="align-items: center; text-align: center;">
    <div class="container-fluid" style="padding-top: 25px; padding-bottom: 5px; text-align: left;">
        <form method="POST" action="{% url 'story6:registerPerson' %}">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <input type="submit" style="margin-left: 502px; background-color: palevioletred;">
        </form>
    </div style="align-items: center">
    <div class="container-fluid" style="padding-bottom: 50px; align-items: center;">
        <h2 style="text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif;"><b><em>click below to see my activity list</em></b></h2>
        <a style= "width:100% ;text-align: center; font-family: Rockwell, “Courier Bold”, Courier, Georgia, Times, “Times New Roman”, serif; color: palevioletred;" href="{% url 'story6:listActivity' %}">here</a>
    </div>
</body>
{% endblock %}